services:
  captain-service:
    build: .
    image: captain-service-image
    container_name: captain-service
    restart: always
    ports:
      - "5002:4002"
    env_file:
      - .env
    networks:
      - users-kafka-net
    
networks:
  users-kafka-net:
    external: true